logging:
  level: info
  format: pretty

http:
  port: 8080
  secure: false

db:
  host: 127.0.0.1
  port: 5432
  database: armaniferrante
  user: armaniferrante
  password: password

auth:
  secret: dummy
